export const ADD_ENTRY = 'ADD_ENTRY';
export const LOAD_ENTRIES = 'LOAD_ENTRIES';

export const ENTRIES_LOAD_DATA_SUCCESS = 'ENTRIES_LOAD_DATA_SUCCESS';
export const ENTRIES_IS_LOADING = 'ENTRIES_IS_LOADING';
export const ENTRIES_HAS_ERRORED = 'ENTRIES_HAS_ERRORED';

export const ADD_AUTHENTICATION_DATA = 'ADD_AUTHENTICATION_DATA';
export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_FIREBASE_DATA = 'GET_FIREBASE_DATA';
